pepysdiary/api/urls.py
from django.urls import include, path

# from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from . import views

app_name = "api"

router = DefaultRouter(trailing_slash=False)
router.register(r"categories", views.CategoryViewSet)
router.register(r"entries", views.EntryViewSet)
router.register(r"topics", views.TopicViewSet)

urlpatterns = [
    path("", include(router.urls)),
    # path("docs/", include_docs_urls(title="The Diary of Samuel Pepys API")),
    path(
        "schema/",
        get_schema_view(
            title="The Diary of Samuel Pepys API",
            url="https://www.pepysdiary.com/",
            version="1.0.0",
        ),
        name="openapi-schema",
    ),
]

pepysdiary/news/urls.py
from django.urls import path, re_path

from .feeds import LatestPostsFeed
from .views import PostArchiveView, PostCategoryArchiveView, PostDetailView

# ALL REDIRECTS are in common/urls.py.

urlpatterns = [
    path("rss/", LatestPostsFeed(), name="post_rss"),
    re_path(
        r"^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<pk>[0-9]+)/$",
        PostDetailView.as_view(),
        name="post_detail",
    ),
    re_path(
        r"^(?P<category_slug>[\w-]+)/$",
        PostCategoryArchiveView.as_view(),
        name="post_category_archive",
    ),
    path("", PostArchiveView.as_view(), name="news"),
]

pepysdiary/up/urls.py
from django.urls import path

from .views import index

app_name = "up"


urlpatterns = [
    path("", index, name="index"),
]

pepysdiary/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pepysdiary.views.home', name='home'),
    # url(r'^pepysdiary/', include('pepysdiary.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

pepysdiary/indepth/models.py
from django.conf import settings
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_comments.moderation import CommentModerator, moderator
from markdown import markdown

from pepysdiary.common.models import PepysModel

from .managers import PublishedArticleManager


class Article(PepysModel):
    """
    An In-Depth Article.
    """

    class Category(models.TextChoices):
        # These are used as slugs in URLs.
        BOOKREVIEWS = "book-reviews", "Book Reviews"
        BACKGROUND = "background", "In-depth Background"
        MISCELLANEOUS = "misc", "Miscellaneous"

    class Status(models.IntegerChoices):
        DRAFT = 10, "Draft"
        PUBLISHED = 20, "Published"

    title = models.CharField(max_length=255, blank=False, null=False)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        default=None,
        on_delete=models.SET_DEFAULT,
        related_name="indepth_articles",
        help_text="Optional.",
    )
    author_name = models.CharField(
        max_length=50,
        blank=True,
        null=False,
        help_text="If Author does not have an account, enter their name here instead",
    )
    author_url = models.URLField(
        max_length=255,
        blank=True,
        null=False,
        help_text="If Author does not have an account, enter optional URL here instead",
    )
    intro = models.TextField(blank=False, null=False, help_text="Can use Markdown.")
    intro_html = models.TextField(
        blank=True,
        null=False,
        help_text="The intro field, with Markdown etc, turned into HTML.",
    )
    text = models.TextField(
        blank=True,
        null=False,
        help_text="Can use Markdown. Any images should be put in "
        "`pepysdiary/indepth/static/img/indepth/`.",
    )
    text_html = models.TextField(
        blank=True,
        null=False,
        help_text="The text field, with Markdown etc, turned into HTML.",
    )
    excerpt = models.TextField(blank=True, null=False)
    date_published = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(
        max_length=50, blank=False, null=False, unique_for_date="date_published"
    )
    comment_count = models.IntegerField(default=0, blank=False, null=False)
    last_comment_time = models.DateTimeField(blank=True, null=True)
    allow_comments = models.BooleanField(blank=False, null=False, default=True)

    status = models.IntegerField(
        blank=False, null=False, choices=Status.choices, default=Status.DRAFT
    )
    category = models.CharField(
        max_length=25,
        blank=False,
        null=False,
        db_index=True,
        choices=Category.choices,
        default=Category.MISCELLANEOUS,
    )

    cover = models.ImageField(
        upload_to="indepth/covers",
        blank=True,
        null=True,
        height_field="cover_height",
        width_field="cover_width",
        help_text="Book cover, if any. 250px wide.",
    )
    cover_width = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    cover_height = models.PositiveSmallIntegerField(blank=True, null=True, default=0)

    item_authors = models.CharField(
        max_length=255,
        blank=True,
        null=False,
        help_text="e.g. if this is a book review, the author(s) of the book",
    )

    # Also see index_components() method.
    search_document = SearchVectorField(null=True)

    objects = models.Manager()
    published_articles = PublishedArticleManager()

    class Meta:
        ordering = ["-date_published"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.intro_html = markdown(self.intro)
        self.text_html = markdown(self.text)
        if self.date_published is None and self.status == self.Status.PUBLISHED:
            # If we're published, and the date_published hasn't been set,
            # then set it.
            self.date_published = timezone.now()

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "article_detail",
            kwargs={
                "year": self.date_published.strftime("%Y"),
                "month": self.date_published.strftime("%m"),
                "day": self.date_published.strftime("%d"),
                "slug": self.slug,
            },
        )

    def index_components(self):
        """Used by common.signals.on_save() to update the SearchVector on
        self.search_document.
        """
        return ((self.title, "A"), (self.intro, "B"), (self.text, "B"))

    @property
    def category_title(self):
        """
        Return the title of this Article's category.
        e.g. "Book reviews".
        """
        categories = {c[0]: c[1] for c in self.Category.choices}
        return categories[self.category]

    @classmethod
    def is_valid_category_slug(cls, slug):
        "Is `slug` a valid Article category?"
        return slug in cls.Category.values

    @classmethod
    def category_slug_to_name(cls, slug):
        """
        Assuming slug is a valid category slug, return the name.
        Else, ''.
        """
        name = ""
        for k, v in cls.Category.choices:
            if k == slug:
                name = v
        return name


class ArticleModerator(CommentModerator):
    email_notification = False
    enable_field = "allow_comments"


moderator.register(Article, ArticleModerator)

pepysdiary/annotations/forms.py
import re

from django_comments.forms import CommentForm

from pepysdiary.annotations.models import Annotation


class AnnotationForm(CommentForm):
    def get_comment_model(self):
        # Use our custom comment model instead of the built-in one.
        return Annotation

    def clean_comment(self):
        """
        Custom tidying of the comment text.
        """
        comment = super().clean_comment()

        # Replace three or more blank lines with two.
        comment = re.sub(r"\n\s*\n", "\n\n", comment)

        # Remove leading and trailing space:
        comment = comment.strip()

        return comment

pepysdiary/encyclopedia/forms.py
from django import forms
from django.contrib import admin
from django.contrib.admin.widgets import (
    FilteredSelectMultiple,
    RelatedFieldWidgetWrapper,
)

from .fields import CategoryMultipleChoiceField
from .models import Category, Topic


class CategoryMapForm(forms.Form):
    """
    The form on the map that shows Topics in a particular category.
    We just have one select field showing a list of available categories.
    """

    category = forms.ChoiceField(
        required=True,
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=Category.objects.map_category_choices(),
    )


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = (
            "title",
            "order_title",
            "summary",
            "summary_author",
            "summary_publication_date",
            "wheatley",
            "tooltip_text",
            "wikipedia_fragment",
            "thumbnail",
            "on_pepys_family_tree",
            "allow_comments",
            "map_category",
            "latitude",
            "longitude",
            "zoom",
            "shape",
            "categories",
        )

    categories = CategoryMultipleChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=RelatedFieldWidgetWrapper(
            FilteredSelectMultiple("categories", is_stacked=False),
            rel=Topic._meta.get_field("categories").remote_field,
            admin_site=admin.site,
        ),
    )

pepysdiary/annotations/views.py
import django_comments
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django_comments.views.utils import next_redirect


@csrf_protect
@login_required
def flag(request, comment_id, next=None):
    """
    Flags a comment. Confirmation on GET, action on POST.

    Our replacement for the default
    https://github.com/django/django-contrib-comments/blob/master/django_comments/views/moderation.py#L15

    Because CommentFlags don't work with custom comments app, which
    is what we have with Annotations.

    Args:
    comment_id - The ID of the comment to flag
    next - Only used when POSTing, the URL to redirect to once done.

    Templates: :template:`comments/flag.html`,
    Context:
        comment
            the flagged `comments.comment` object
    """
    comment = get_object_or_404(
        django_comments.get_model(),
        pk=comment_id,
        site__pk=get_current_site(request).pk,
    )

    # Flag on POST
    if request.method == "POST":
        perform_flag(request, comment)
        return next_redirect(
            request, fallback=next or "comments-flag-done", c=comment.pk
        )

    # Render a form on GET
    else:
        return render(request, "comments/flag.html", {"comment": comment, "next": next})


def perform_flag(request, comment):
    """Similarly, our replacement for the default
    https://github.com/django/django-contrib-comments/blob/master/django_comments/views/moderation.py#L99
    so it dirtily sends me an email, rather than create an actual
    CommentFlag.
    """

    comment_url = request.build_absolute_uri(comment.get_absolute_url())
    url_name = f"admin:{comment._meta.app_label}_{comment._meta.model_name}_change"
    admin_url = reverse(url_name, args=[comment.id])
    admin_url = request.build_absolute_uri(admin_url)

    message = f"""Flagged comment: {comment_url}

Admin:           {admin_url}

Flagged by:      {request.user.name} <{request.user.email}>
"""

    send_mail(
        "Pepys' Diary Flag",
        message,
        settings.DEFAULT_FROM_EMAIL,
        [settings.COMMENT_FLAG_EMAIL],
        fail_silently=False,
    )

pepysdiary/api/views.py
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from rest_framework import viewsets
from rest_framework.views import exception_handler

from pepysdiary.diary.models import Entry
from pepysdiary.diary.views import date_from_string
from pepysdiary.encyclopedia.models import Category, Topic

from .serializers import (
    CategoryDetailSerializer,
    CategoryListSerializer,
    EntryDetailSerializer,
    EntryListSerializer,
    TopicDetailSerializer,
    TopicListSerializer,
)


def custom_exception_handler(exc, context):
    # Call REST framework's default exception handler first,
    # to get the standard error response.
    response = exception_handler(exc, context)

    # Now add the HTTP status code to the response.
    if response is not None:
        response.data["status_code"] = response.status_code

    return response


class CachedReadOnlyModelViewSet(viewsets.ReadOnlyModelViewSet):
    "Parent class that adds caching to the list() and retrieve() methods."

    @method_decorator(cache_page(60 * 15))
    @method_decorator(vary_on_cookie)
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

    @method_decorator(cache_page(60 * 15))
    @method_decorator(vary_on_cookie)
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)


class CategoryViewSet(CachedReadOnlyModelViewSet):
    """
    Fetch one or more Encyclopedia Categories.

    Categories are in a tree structure and so each one has zero or more
    `parents` and `children`.

    Each Category contains zero or more Topics.

    Add the `page` to get further pages of results, e.g.:

    * `categories?page=2`

    Fetch more data about a single Category using its slug, e.g.:

    * `categories/london`
    """

    queryset = Category.objects.all().order_by("slug")
    serializer_class = CategoryListSerializer
    lookup_field = "slug"
    lookup_url_kwarg = "category_slug"

    def get_serializer_class(self):
        if self.action == "retrieve":
            return CategoryDetailSerializer
        else:
            return self.serializer_class


class EntryViewSet(CachedReadOnlyModelViewSet):
    """
    Fetch one or more Diary Entries.

    Each Entry mentions zero or more Encyclopedia Topics.

    Add the `page` to get further pages of results, e.g.:

    * `entries?page=2`

    Restrict the list to specific dates, or spans of dates, using the
    `start` and `end` parameters. Entries span from `1660-01-01` to
    `1669-05-31` inclusive. e.g.:

    * `entries?start=1661-01-01` – Everything on and after 1st Jan 1661
    * `entries?end=1661-12-31` – Everything on and before 31st Dec 1661
    * `entries?start=1661-01-01&end=1661-12-31` – Everything from 1661

    Fetch more data about a single Entry using its date, e.g.:

    * `entries/1660-12-31`
    """

    queryset = Entry.objects.all().order_by("diary_date")
    serializer_class = EntryListSerializer
    lookup_field = "diary_date"
    lookup_url_kwarg = "entry_date"

    def get_serializer_class(self):
        if self.action == "retrieve":
            return EntryDetailSerializer
        else:
            return self.serializer_class

    def get_queryset(self):
        """
        If retrieving a list of Entries, optionally filter by start and
        end query string arguments.
        """
        queryset = self.queryset

        if self.action == "list":
            start = self.request.query_params.get("start")
            end = self.request.query_params.get("end")

            if start:
                parts = start.split("-")
                start_date = date_from_string(
                    parts[0], "%Y", parts[1], "%m", parts[2], "%d", "-"
                )
                queryset = queryset.filter(diary_date__gte=start_date)

            if end:
                parts = end.split("-")
                end_date = date_from_string(
                    parts[0], "%Y", parts[1], "%m", parts[2], "%d", "-"
                )
                queryset = queryset.filter(diary_date__lte=end_date)

        return queryset


class TopicViewSet(CachedReadOnlyModelViewSet):
    """
    Fetch one or more Encyclopedia Topics.

    Each Topic is contained in one or more Categories.

    Each Topic is mentioned in one or more Diary Entries.

    Add the `page` to get further pages of results, e.g.:

    * `topics?page=2`

    Fetch more data about a single Topic using its numeric ID, e.g.:

    * `topics/796`
    """

    queryset = Topic.objects.all().order_by("id")
    serializer_class = TopicListSerializer
    lookup_field = "id"
    lookup_url_kwarg = "topic_id"

    def get_serializer_class(self):
        if self.action == "retrieve":
            return TopicDetailSerializer
        else:
            return self.serializer_class

pepysdiary/templates/encyclopedia/category_detail.html
{% extends "common/layouts/base.html" %}
{% load humanize %}

{% block encyclopedia_nav_active %}active{% endblock %}
{% block encyclopedia_index_nav_active %}active{% endblock %}

{% block title %}{{ category.title }}{% endblock %}}
{% block header_title %}{{ category.title }}{% endblock %}}

{% block breadcrumbs %}
	{% include 'encyclopedia/inc/category_breadcrumb.html' %}
{% endblock breadcrumbs %}

{% block main_content %}

	{% if category.get_children_count %}
		<div class="subcategories clearfix">
			<h2>Subcategories</h2>

			{% load partition_tags %}
			{% make_rows category.get_children 2 5 as rows %}
			{% for column in rows %}
				<div class="col-sm-6">
					<ul>
						{% for cat in column %}
							<li><a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>
								{% comment %}
									{% if cat.get_children_count %}<small>({{ cat.get_children_count }} categor{{ cat.get_children_count|pluralize:"y,ies" }})</small>{% endif %}
								{% endcomment %}
								{% if cat.topic_count %}<small>({{ cat.topic_count|intcomma }} topic{{ cat.topic_count|pluralize }})</small>{% endif %}</li>
						{% endfor %}
					</ul>
				</div>
			{% endfor %}
		</div> <!-- .subcategories -->
	{% endif %}

    {% if topics %}
        <h2>{{ topics|length|intcomma }} Topic{{ topics|pluralize }}</h2>

        {% if topics.count < 25 %}
            {# Just a simple list because there's not many. #}
            <ul>
                {% for t in topics %}
                    <li><a href="{{ t.get_absolute_url }}">{{ t.order_title }}</a></li>
                {% endfor %}
            </ul>

        {% else %}
            {# There are lots, so we separate by first letter. #}

            {# For the top list of letters, we use two prepared lists from the view. #}
            <ul class="pagination pagination-sm">
                {% for az in all_letters %}
                    {% if az in used_letters %}
                        <li><a href="#{{ az }}">{{ az }}</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">{{ az }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>

            {# For the list we regroup the topics by first letter. #}
            {% regroup topics by order_title|first|upper as letters %}

            {% for letter in letters %}
                <h3 id="{{ letter.grouper }}">{{ letter.grouper }}</h3>
                <ul>
                    {% for t in letter.list %}
                        <li><a href="{{ t.get_absolute_url }}">{{ t.order_title }}</a></li>
                    {% endfor %}
                </ul>
            {% endfor %}

        {% endif %}

    {% endif %}

{% endblock %}


{% block sidebar %}
{% endblock sidebar %}

pepysdiary/templates/encyclopedia/category_list.html
{% extends "common/layouts/base.html" %}
{% load humanize %}
{% load widget_tags %}

{% block encyclopedia_nav_active %}active{% endblock %}
{% block encyclopedia_index_nav_active %}active{% endblock %}

{% block title %}Encyclopedia{% endblock %}}
{% block header_title %}Encyclopedia{% endblock %}}

{% block main_content %}

	<p class="lead">Information about {{ topic_count|intcomma }} people, places and things in Pepys’ time.</p>

	{% for category, info in categories %}
	    {% if info.open %}
	        <ul><li>
	    {% else %}
	        </li><li>
	    {% endif %}

	    <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>

		{% if category.topic_count %}<small>({{ category.topic_count|intcomma }})</small>{% endif %}

	    {% for close in info.close %}
	        </li></ul>
	    {% endfor %}
	{% endfor %}

{% endblock main_content %}


{% block sidebar_content %}

	{% category_map_link %}

	{% family_tree_link %}

	{% pepys_wealth_link %}

	{% detailed_topics %}

	{% latest_topics quantity=5 %}

{% endblock sidebar_content %}

pepysdiary/templates/encyclopedia/category_map.html
{% extends "common/layouts/base_full_width.html" %}

{% block encyclopedia_nav_active %}active{% endblock %}
{% block encyclopedia_map_nav_active %}active{% endblock %}

{% block title %}Map{% if category %} of {{ category }}{% endif %}{% endblock %}}
{% block page_header %}
	<header class="page-header page-header-map">
		<form action="{% url 'category_map' %}" method="post" class="form-inline" id="category-form" role="form">
			{% csrf_token %}
			<h1 class="map-form-title">Map showing: <span class="sr-only">{{ category.title }}</span></h1>
      {% if form.category.errors or form.non_field_errors %}
        <ul>
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
          {% for error in form.category.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
			<label for="id_category" class="sr-only">Select category:</label>
			{{ form.category }}
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</header>
{% endblock %}


{% load include_tags %}
{% block extra_css %}
	{% include_maps_css %}
{% endblock %}
{% block extra_javascript_includes %}
	{% include_maps_js %}
{% endblock %}


{% block extra_jquery %}
	pepys.category.init_map({
		category_id: {{ category.id }},
		valid_map_category_ids: [
			{% for id in valid_map_category_ids %}
				{{ id }}{% if forloop.last %}{% else %},{% endif %}
			{% endfor %}
		],
		topics: [
			{% for topic in topics %}
				{
					id: {{ topic.id }},
					title: "{{ topic.title|escapejs|safe }}",
					tooltip_text: "{{ topic.tooltip_text|escapejs }}",
					{% if topic.id in pepys_homes_ids %}
						pepys_home: true,
					{% endif %}
					{% if topic.has_polygon %}
						polygon: "{{ topic.shape|escapejs }}",
					{% endif %}
					{% if topic.has_path %}
						path: "{{ topic.shape|escapejs }}",
					{% endif %}
					latitude: {{ topic.latitude }},
					longitude: {{ topic.longitude }},
					url: "{{ topic.get_absolute_url }}"
				}{% if forloop.last %}{% else %},{% endif %}
			{% endfor %}
		]
	});
{% endblock %}


{% block main_content %}

  {% include "encyclopedia/inc/map.html" with size="big" only %}

{% endblock main_content %}

pepysdiary/templates/encyclopedia/topic_map.html
{% extends "base_full_width.html" %}
{% load url from future %}

{% block encyclopedia_nav_active %}active{% endblock %}
{% block encyclopedia_map_nav_active %}active{% endblock %}

{% block title %}Map{% endblock %}}
{% block header_title %}Map{% endblock %}}


{% load include_tags %}
{% block extra_css %}
	{% include_leaflet_css %}
{% endblock %}
{% block extra_javascript_includes %}
	{% include_leaflet_js %}
{% endblock %}


{% block extra_jquery %}
	pepys.category.init_map({
		category_id: {{ category.id }},
		map_categories: {
			{% for category in map_categories %}
				"{{ category.id }}": "{{ category.title|escapejs }}"{% if forloop.last %}{% else %},{% endif %}
			{% endfor %}
		}
	});
{% endblock %}


{% block main_content %}

	<div id="map-frame" class="map-frame-big"></div>

{% endblock main_content %}